Update schema descriptions
yuvipanda/jupyterhub-configurator pull request #11
Opened 2022-03-04 00:17 UTC by choldgraf

This updates a few of the schema descriptions so that they are more clear.

- The `docker image` field now provides guidance for the structure that the value should take (to avoid confusion like in https://github.com/2i2c-org/infrastructure/issues/1032#issuecomment-1058674360).
- The descriptions of each user interface now re-use the content that is at try.jupyter.org .

2022-03-04 00:20 UTC, choldgraf commented on frontend/src/schema.json
> +      "help": "Should be of the form <docker registry>/<org>/<name>:<tag>. E.g., quay.io/2i2c/myimagename:cb5757e7c9f8. Leave this blank to use the default."
```suggestion
      "help": "For example: quay.io/2i2c/myimagename:cb5757e7c9f8. Leave this blank to use the default."
```

2022-03-04 07:53 UTC, GeorgianaElena approved these changes
🚀

2022-03-09 12:43 UTC, damianavila approved these changes

2022-03-11 05:47 UTC, yuvipanda commented
This also needs the frontend js to be rebuilt I think before it can be deployed... Need to automate that.

2022-03-11 16:35 UTC, damianavila requested changes
As per @yuvipanda's last comment, this one needs the JS to be rebuilt.

2022-03-11 17:15 UTC, choldgraf commented
OK I _think_ I just did this, let me know if I got it wrong.

While I was at it, I updated the contributing docs a bit, because they were a little unclear to me :-)

2022-03-11 19:52 UTC, manics commented
> Need to automate that.

I had a go at copying https://github.com/jupyterhub/nbgitpuller/pull/211 + https://github.com/jupyterhub/nbgitpuller/pull/222 to this repo (untested, and has some bugs):
https://github.com/yuvipanda/jupyterhub-configurator/compare/main...manics:package?expand=1

It's a bit more complicated than nbgitpuller because of the extra webpack/babel/css config and subdirectory.

2022-03-11 19:56 UTC, choldgraf commented
@manics I found it confusing too haha, that's why I tried to document a little bit more.

This feels like something that `nox` or `tox` could be useful for. Then a person could just run something like `nox -s compile` and it would (1) install `npm` in a virtual environment if needed, (2) run the proper `npm` commands to build the assets needed. We use this in the Jupyter Book world a lot and it helps reduce confusion associated with installing NPM environments

2022-03-11 20:47 UTC, manics commented
The idea behind Jupyter-packaging (or the equivalent code) is to include the npm build commands in setup.py so that usual `pip install .` takes care of almost everything, and you never need to commit the generated JS assets- they're generated and packaged automatically into the wheel.

2022-03-11 20:55 UTC, yuvipanda commented
@manics wow that would be *awesome*. Can you make a PR too?

2022-03-11 21:05 UTC, manics commented
Will do when I get time to test it (assuming it works!)

2022-03-11 21:56 UTC, choldgraf commented
@manics you should check out the Sphinx Theme Builder that @pradyunsg built, it uses the `pyproject.toml` build standard to include an npm environment with an install. It is lovely: https://github.com/pradyunsg/sphinx-theme-builder

2022-03-12 20:20 UTC, manics commented
`pyproject.toml`/pep517  is nice, but if you're using setuptools you'll loose the option of an editable install (`pip install -e .`) :cry: https://github.com/pypa/setuptools/issues/2816 

I've therefore gone for a build without pep517 for now in https://github.com/yuvipanda/jupyterhub-configurator/pull/13
If you merge your current PR I can update the docs in my PR

2022-03-12 20:41 UTC, choldgraf commented
@manics yeah, we have switched to using flit for builds in jupyter book, which gives you editable builds 🙂

For this PR, I think it's good to go? I don't know that I can merge into @yuvipanda 's repo though

2022-03-13 07:41 UTC, pradyunsg commented
> `pyproject.toml`/pep517 is nice, but if you're using setuptools you'll loose the option of an editable install (`pip install -e .`) 😢 [pypa/setuptools#2816](https://github.com/pypa/setuptools/issues/2816)

Yes, but if you're doing something like this in a custom build backend, you won't be relying on setuptools to perform the build for you. Basically, instead of:

> The idea behind Jupyter-packaging (or the equivalent code) is to include the npm build commands in setup.py so the usual `pip install .`

You'd end up doing for sphinx-theme-builder is doing -- running npm commands _before_ packaging things up yourself.

2022-04-05 22:46 UTC, choldgraf commented
Can somebody tell me if there's anything else I should do, or if we can merge this?

2024-03-21 17:25 UTC, yuvipanda commented
Unfortunately this project is an architectural dead end - see https://github.com/2i2c-org/infrastructure/issues/2564. Going to close this one out.

2024-03-21 17:25 UTC, closed without merging